### ISSUE TITLE
Can't access table

### ISSUE THREAD

**Issue by silas229** [stefan-niedermann/nextcloud-tables#112]
### This issue respects the following points:

- [X] I have searched for existing issues
- [X] The issue affects the Tables Android app, neither the [Tables server app](https://github.com/nextcloud/tables/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

Refresh the tables, the following error occurs (see stacktrace)
Additionally, table 2 is also not selectable, although I can select it in the web ui. All other tables are selectable in the app.

This could be a bug in connection with the server app

### Tables Android version

1.1.3

### Tables server version

0.7.5

### Nextcloud Android version

3.29.3

### Nextcloud version

29

### Device

Oneplus Nord 2

### Android Version

13

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 1.1.3
App Version Code: 1001003
Server App Version: 0.7.5
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

---

OS Version: 4.19.191+(R.17dbfdc-1)
OS API Level: 33
Device: OP515BL1
Manufacturer: OnePlus
Model (and Product): DN2103 (DN2103EEA)

---

java.util.concurrent.CompletionException: it.niedermann.nextcloud.tables.remote.exception.ServerNotAvailableException: SERVER_ERROR: Could not fetch rows for table with remote ID 2
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel.lambda$synchronizeAccountAndTables$0(ViewTableViewModel.java:50)
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel.$r8$lambda$i2kk9gr05c1DH47vg5OpNfQicrE(Unknown Source:0)
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel$$ExternalSyntheticLambda3.get(D8$$SyntheticClass:0)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1744)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: it.niedermann.nextcloud.tables.remote.exception.ServerNotAvailableException: SERVER_ERROR: Could not fetch rows for table with remote ID 2
	at it.niedermann.nextcloud.tables.repository.ServerErrorHandler.handle(ServerErrorHandler.java:43)
	at it.niedermann.nextcloud.tables.repository.ServerErrorHandler.handle(ServerErrorHandler.java:33)
	at it.niedermann.nextcloud.tables.repository.sync.RowSyncAdapter.lambda$pullRemoteChanges$0(RowSyncAdapter.java:143)
	at it.niedermann.nextcloud.tables.repository.sync.RowSyncAdapter.$r8$lambda$NVUEwW7WgE5OgRiVNjH15T1-wvc(Unknown Source:0)
	at it.niedermann.nextcloud.tables.repository.sync.RowSyncAdapter$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

```

PHP Error log on server:
[index] Fehler: OCA\Tables\Service\RowService::findAllByTable(): Argument #2 ($userId) must be of type string, null given, called in /var/www/nextcloud/apps/tables/lib/Controller/Api1Controller.php on line 1005 in file '/var/www/nextcloud/apps/tables/lib/Service/RowService.php' line 75
	GET /index.php/apps/tables/api/1/tables/1/rows?limit=1000&offset=0

**Comment by stefan-niedermann** [comment]
Should be fixed in `2.0.2`. Please reopen in case the issue still occurs.

**Comment by silas229** [comment]
Works now!
