### ISSUE TITLE
Error after viewing a edited table

### ISSUE THREAD

**Issue by Markoise** [stefan-niedermann/nextcloud-tables#13]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
This comes after viewing a edited table.

```
Full Crash:

App Version: 1.1.0
App Version Code: 1001000
App Flavor: play

Files App Version Code: 30250090 (PROD)

---

OS Version: 5.10.157-android13-4-00002-g0eacbbcce3d5-ab9881766(10204971)
OS API Level: 33
Device: panther
Manufacturer: Google
Model (and Product): Pixel 7 (panther)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.recyclerview.widget.RecyclerView$ViewHolder com.evrencoskun.tableview.adapter.recyclerview.CellRecyclerView.findViewHolderForAdapterPosition(int)' on a null object reference
	at com.evrencoskun.tableview.handler.SelectionHandler.changeVisibleCellViewsBackgroundForColumn(SelectionHandler.java:353)
	at com.evrencoskun.tableview.handler.SelectionHandler.selectedColumnHeader(SelectionHandler.java:235)
	at com.evrencoskun.tableview.handler.SelectionHandler.setSelectedColumnPosition(SelectionHandler.java:92)
	at com.evrencoskun.tableview.listener.itemclick.ColumnHeaderRecyclerViewItemClickListener.clickAction(ColumnHeaderRecyclerViewItemClickListener.java:63)
	at com.evrencoskun.tableview.listener.itemclick.AbstractItemClickListener$1.onSingleTapConfirmed(AbstractItemClickListener.java:72)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:333)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Versions**

 - Nextcloud: 26.0.2
 - Nextcloud Tables: 0.5.1
 - Nextcloud Android: 3.25.0
 - Nextcloud Android Tables: 1.1.0

**Smartphone (please complete the following information):**
- Device: Pixel 7
- Android-Version: 13
- App-Store:
  - [x] Google Play Store
  - [x] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Should be fixed in `2.0.2`. Please reopen in case the issue still occurs.
