### ISSUE TITLE
Tables not sync

### ISSUE THREAD

**Issue by otapol** [stefan-niedermann/nextcloud-tables#136]
### This issue respects the following points:

- [X] I have searched for existing issues
- [X] The issue affects the Tables Android app, neither the [Tables server app](https://github.com/nextcloud/tables/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

```
App Version: 1.1.3
App Version Code: 1001003
Server App Version: 0.6.6
App Flavor: fdroid

Files App Version Code: 30300490 (PROD)

---

OS Version: 5.15.170-android14-11-gf0d7580141e5(2024111800)
OS API Level: 35
Device: shiba
Manufacturer: Google
Model (and Product): Pixel 8 (shiba)

---

java.util.concurrent.CompletionException: it.niedermann.nextcloud.tables.remote.exception.ServerNotAvailableException: SERVER_ERROR: Could not push local changes for row 268
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel.lambda$synchronizeAccountAndTables$0(ViewTableViewModel.java:50)
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel.$r8$lambda$i2kk9gr05c1DH47vg5OpNfQicrE(Unknown Source:0)
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel$$ExternalSyntheticLambda3.get(D8$$SyntheticClass:0)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1744)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: it.niedermann.nextcloud.tables.remote.exception.ServerNotAvailableException: SERVER_ERROR: Could not push local changes for row 268
	at it.niedermann.nextcloud.tables.repository.ServerErrorHandler.handle(ServerErrorHandler.java:43)
	at it.niedermann.nextcloud.tables.repository.ServerErrorHandler.handle(ServerErrorHandler.java:33)
	at it.niedermann.nextcloud.tables.repository.sync.RowSyncAdapter.pushLocalChanges(RowSyncAdapter.java:90)
	at it.niedermann.nextcloud.tables.repository.TablesRepository.pushLocalChanges(TablesRepository.java:82)
	at it.niedermann.nextcloud.tables.repository.TablesRepository.synchronizeTables(TablesRepository.java:73)
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel.lambda$synchronizeAccountAndTables$0(ViewTableViewModel.java:47)
	... 6 more

```

### Tables Android version

GrapneOS

### Tables server version

1.1.3

### Nextcloud Android version

GrapneOS

### Nextcloud version

7

### Device

Google Pixel 8

### Android Version

14

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 1.1.3
App Version Code: 1001003
Server App Version: 0.6.6
App Flavor: fdroid

Files App Version Code: 30300490 (PROD)

---

OS Version: 5.15.170-android14-11-gf0d7580141e5(2024111800)
OS API Level: 35
Device: shiba
Manufacturer: Google
Model (and Product): Pixel 8 (shiba)

---

java.util.concurrent.CompletionException: it.niedermann.nextcloud.tables.remote.exception.ServerNotAvailableException: SERVER_ERROR: Could not push local changes for row 268
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel.lambda$synchronizeAccountAndTables$0(ViewTableViewModel.java:50)
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel.$r8$lambda$i2kk9gr05c1DH47vg5OpNfQicrE(Unknown Source:0)
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel$$ExternalSyntheticLambda3.get(D8$$SyntheticClass:0)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1744)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: it.niedermann.nextcloud.tables.remote.exception.ServerNotAvailableException: SERVER_ERROR: Could not push local changes for row 268
	at it.niedermann.nextcloud.tables.repository.ServerErrorHandler.handle(ServerErrorHandler.java:43)
	at it.niedermann.nextcloud.tables.repository.ServerErrorHandler.handle(ServerErrorHandler.java:33)
	at it.niedermann.nextcloud.tables.repository.sync.RowSyncAdapter.pushLocalChanges(RowSyncAdapter.java:90)
	at it.niedermann.nextcloud.tables.repository.TablesRepository.pushLocalChanges(TablesRepository.java:82)
	at it.niedermann.nextcloud.tables.repository.TablesRepository.synchronizeTables(TablesRepository.java:73)
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel.lambda$synchronizeAccountAndTables$0(ViewTableViewModel.java:47)
	... 6 more

```

**Comment by stefan-niedermann** [comment]
Should be fixed in `2.0.2`. Please reopen in case the issue still occurs.
