### ISSUE TITLE
Error 520 after select Account

### ISSUE THREAD

**Issue by Sputnikchen** [stefan-niedermann/nextcloud-tables#141]
### This issue respects the following points:

- [X] I have searched for existing issues
- [X] The issue affects the Tables Android app, neither the [Tables server app](https://github.com/nextcloud/tables/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. Install
2. Open App
3. Select Account
4. Click "OK"
5. Error 520

### Expected behavior

Start App

### Tables Android version

1.1.3

### Tables server version

0.8.1

### Nextcloud Android version

3.29.2

### Nextcloud version

30.0.3

### Device

Xiaomi Mi 11T Pro

### Android Version

14

### App Store

- [x] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 1.1.3
App Version Code: 1001003
Server App Version: null
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

---

OS Version: 5.4.259-qgki-g6f25851aad0d(V816.0.6.0.UKDEUXM)
OS API Level: 34
Device: vili
Manufacturer: Xiaomi
Model (and Product): 2107113SG (vili_eea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 520
	at it.niedermann.nextcloud.tables.repository.ServerErrorHandler.handle(ServerErrorHandler.java:53)
	at it.niedermann.nextcloud.tables.repository.ServerErrorHandler.handle(ServerErrorHandler.java:29)
	at it.niedermann.nextcloud.tables.repository.AccountRepository.synchronizeCapabilities(AccountRepository.java:148)
	at it.niedermann.nextcloud.tables.repository.AccountRepository.synchronizeAccount(AccountRepository.java:97)
	at it.niedermann.nextcloud.tables.ui.importaccount.ImportAccountViewModel.lambda$createAccount$0(ImportAccountViewModel.java:46)
	at it.niedermann.nextcloud.tables.ui.importaccount.ImportAccountViewModel.$r8$lambda$PB7MyuUtAB6f_3La_VgFoeGeLgk(Unknown Source:0)
	at it.niedermann.nextcloud.tables.ui.importaccount.ImportAccountViewModel$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.RuntimeException: 
	... 12 more

```

**Comment by stefan-niedermann** [comment]
Should be fixed in `2.0.2`. Please reopen in case the issue still occurs.
