### ISSUE TITLE
Crash on refresh 

### ISSUE THREAD

**Issue by AndyScherzinger** [stefan-niedermann/nextcloud-tables#23]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Crash on refresh of a table 

1. Pull to. Refresh on any table

**Expected behavior**

Sync

**Screenshots**

**Versions**

 - Nextcloud: 27.0.1
 - Nextcloud Tables: latest beta
 - Nextcloud Android: master
 - Nextcloud Android Tables: 1.1.2

**Smartphone (please complete the following information):**
- Device: OP9Pro
- Android-Version: 13
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

```
App Version: 1.1.2
App Version Code: 1001002
Server App Version: 27.1.0
App Flavor: fdroid

Files App Version Code: 30270000 (PROD)

---

OS Version: 5.4.210-qgki-gb141df486402(R.11f3c87-1-5605)
OS API Level: 33
Device: OnePlus9Pro
Manufacturer: OnePlus
Model (and Product): LE2123 (OnePlus9Pro_EEA)

---

java.util.concurrent.CompletionException: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 520
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel.lambda$synchronizeAccountAndTables$0$it-niedermann-nextcloud-tables-ui-table-view-ViewTableViewModel(ViewTableViewModel.java:50)
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel$$ExternalSyntheticLambda1.get(Unknown Source:4)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1676)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 520
	at it.niedermann.nextcloud.tables.repository.ServerErrorHandler.handle(ServerErrorHandler.java:53)
	at it.niedermann.nextcloud.tables.repository.ServerErrorHandler.handle(ServerErrorHandler.java:29)
	at it.niedermann.nextcloud.tables.repository.AccountRepository.synchronizeCapabilities(AccountRepository.java:148)
	at it.niedermann.nextcloud.tables.repository.AccountRepository.synchronizeAccount(AccountRepository.java:97)
	at it.niedermann.nextcloud.tables.ui.table.view.ViewTableViewModel.lambda$synchronizeAccountAndTables$0$it-niedermann-nextcloud-tables-ui-table-view-ViewTableViewModel(ViewTableViewModel.java:46)
	... 5 more
Caused by: java.lang.RuntimeException: 
	... 10 more

```

**Comment by Fruitsmart** [comment]
Hey, I have the same problem too. I have Android 14. Is there already a solution for this?

**Comment by pawlosck** [comment]
I have the same problem, but in my case problem happen after remove table on the server.
After that, I created similar tab, but one column changed type and added second column.
I couldn't download new tab. Generally, I couldn't do anything. I had to reinstall app and login again to download current tables.

**Comment by ostasevych** [comment]
It seems the app development is abandoned completely :(

**Comment by stefan-niedermann** [comment]
@ostasevych nothing could be more wrong. On the `dev` branch a complete rewrite is happening with a diff of 10k+ lines. It currently does not make any sense to track the currently reported issues due to the large changes that have been made there. I keep the issues open though to ensure they alle will be fixed with the rewrite.

**Comment by stefan-niedermann** [comment]
Should be fixed in `2.0.2`. Please reopen in case the issue still occurs.
