### ISSUE TITLE
SSO issue

### ISSUE THREAD

**Issue by Djey51** [stefan-niedermann/nextcloud-tables#35]
**Stacktrace**

```
App Version: 1.1.2
App Version Code: 1001002
Server App Version: null
App Flavor: fdroid

Files App Version Code: 30260090 (PROD)

---

OS Version: 5.10.177-android13-4-00003-ga7208022a7ea-ab10815828(23502000)
OS API Level: 34
Device: panther
Manufacturer: Google
Model (and Product): Pixel 7 (panther)

---

it.niedermann.nextcloud.tables.remote.exception.ServerNotAvailableException: NOT_INSTALLED
	at it.niedermann.nextcloud.tables.repository.AccountRepository.synchronizeCapabilities(AccountRepository.java:129)
	at it.niedermann.nextcloud.tables.repository.AccountRepository.synchronizeAccount(AccountRepository.java:97)
	at it.niedermann.nextcloud.tables.ui.importaccount.ImportAccountViewModel.lambda$createAccount$0$it-niedermann-nextcloud-tables-ui-importaccount-ImportAccountViewModel(ImportAccountViewModel.java:46)
	at it.niedermann.nextcloud.tables.ui.importaccount.ImportAccountViewModel$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by stefan-niedermann** [comment]
You don't have installed Nextcloud Tables on your server, do you?

**Comment by Djey51** [comment]
No because I'm using my.cloudeezy.com as server provider.
Is it a problem?

19 déc. 2023 07:51:13 Niedermann IT-Dienstleistungen ***@***.***>:

**Comment by stefan-niedermann** [comment]
Obviously yes. I recommend you to read descriptions of Android apps *before* installing them, especially if they have a `Requirements` section 😉
