### ISSUE TITLE
null Selection throws an error

### ISSUE THREAD

**Issue by hamuchen** [stefan-niedermann/nextcloud-tables#36]
If you create a selection column and don't select a default selection, the selection is not shown and the app throws an error.

**Expected behavior**
Let me chose a selection

**Screenshots**
Settings in Nextcloud:
![2023-12-24_103204](https://github.com/stefan-niedermann/nextcloud-tables/assets/3384168/1ffbba7c-6279-4173-a87c-f1e5842289ec)
Error in App:
![Screenshot_20231224-103219](https://github.com/stefan-niedermann/nextcloud-tables/assets/3384168/4d01d036-18c5-4ee5-ae28-4bf88731302d)
Changing the Settings to this:
![2023-12-24_103331](https://github.com/stefan-niedermann/nextcloud-tables/assets/3384168/d3b133cb-76ba-4ff2-8340-ddae2a2eee6a)
App works with a default selection
![Screenshot_20231224-103356](https://github.com/stefan-niedermann/nextcloud-tables/assets/3384168/f0b7c2a1-0a46-4802-bf77-dae21f99ac9b)

**Versions**

 - Nextcloud: 27.1.5
 - Nextcloud Tables: 0.6.5
 - Nextcloud Android: 3.26.0
 - Nextcloud Android Tables: 1.1.2

**Smartphone (please complete the following information):**
- Device: BB Key2
- Android-Version: 8.1.0
- App-Store:
  - [X] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**
```
App Version: 1.1.2
App Version Code: 1001002
App Flavor: play

Files App Version Code: 30260090 (PROD)

---

OS Version: 4.4.78-perf+(ACW142)
OS API Level: 27
Device: bbf100
Manufacturer: BlackBerry
Model (and Product): BBF100-6 (bbf100dsglobal)

---

java.lang.NumberFormatException: For input string: "null"
	at java.lang.Long.parseLong(Long.java:590)
	at java.lang.Long.parseLong(Long.java:632)
	at it.niedermann.nextcloud.tables.ui.row.type.selection.SelectionEditor.setValue(SelectionEditor.java:84)
	at it.niedermann.nextcloud.tables.ui.row.type.selection.SelectionEditor.onCreate(SelectionEditor.java:49)
	at it.niedermann.nextcloud.tables.ui.row.ColumnEditView.<init>(ColumnEditView.java:73)
	at it.niedermann.nextcloud.tables.ui.row.type.selection.SelectionEditor.<init>(SelectionEditor.java:40)
	at it.niedermann.nextcloud.tables.ui.row.ColumnEditView$Factory.create(ColumnEditView.java:175)
	at it.niedermann.nextcloud.tables.ui.row.EditRowActivity.lambda$onCreate$1$it-niedermann-nextcloud-tables-ui-row-EditRowActivity(EditRowActivity.java:75)
	at it.niedermann.nextcloud.tables.ui.row.EditRowActivity$$ExternalSyntheticLambda0.accept(Unknown Source:8)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:664)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:640)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:450)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6558)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

```

Cheers
hamu

**Comment by stefan-niedermann** [comment]
Thank you for the report. The fix will be published with `1.1.3`.
