### ISSUE TITLE
Text 'none' could not be parsed at index 0

### ISSUE THREAD

**Issue by 02walshe** [stefan-niedermann/nextcloud-tables#97]
### This issue respects the following points:

- [X] I have searched for existing issues
- [X] The issue affects the Tables Android app, neither the [Tables server app](https://github.com/nextcloud/tables/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. Open App
2. Click 'Choose Account' button
3. Select Nextcloud account
4. Click Ok button
5. Select 'Allow' when prompted
6. Error is thrown after 'Importing Tables' stage
7. Stacktrace is shown.
8. Tables are not loaded, and taken back to 'Choose Account' screen

### Expected behavior

App proceeds to load tables from Nextcloud instance.

### Tables Android version

1.1.2

### Tables server version

0.7.4

### Nextcloud Android version

3.29.2

### Nextcloud version

29.0.3

### Device

Samsung Galaxy S23 Ultra

### Android Version

14

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 1.1.2
App Version Code: 1001002
Server App Version: 29.0.0
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

---

OS Version: 5.15.123-android13-8-28577312-abS918BXXS5CXE9(S918BXXS5CXE9)
OS API Level: 34
Device: dm3q
Manufacturer: samsung
Model (and Product): SM-S918B (dm3qxeea)

---

java.time.format.DateTimeParseException: Text 'none' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2050)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1878)
	at it.niedermann.nextcloud.tables.remote.adapter.DataAdapter.deserialize(DataAdapter.java:116)
	at it.niedermann.nextcloud.tables.repository.sync.RowSyncAdapter.lambda$pullRemoteChanges$0$it-niedermann-nextcloud-tables-repository-sync-RowSyncAdapter(RowSyncAdapter.java:176)
	at it.niedermann.nextcloud.tables.repository.sync.RowSyncAdapter$$ExternalSyntheticLambda2.run(Unknown Source:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by 02walshe** [comment]
Looks like v1.1.3 of the Android app has fixed this version 👍
